// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pika.DataLayer;

#nullable disable

namespace Pika.DataLayer.Migrations
{
    [DbContext(typeof(PikaDataContext))]
    [Migration("20220424051033_NullableRootEntry")]
    partial class NullableRootEntry
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EntryDbModelObjectiveDbModel", b =>
                {
                    b.Property<Guid>("EntriesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ObjectivesId")
                        .HasColumnType("uuid");

                    b.HasKey("EntriesId", "ObjectivesId");

                    b.HasIndex("ObjectivesId");

                    b.ToTable("EntryDbModelObjectiveDbModel");
                });

            modelBuilder.Entity("Pika.DataLayer.Model.DomainDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RootEntryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RootEntryId");

                    b.ToTable("Domains");
                });

            modelBuilder.Entity("Pika.DataLayer.Model.EntryDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("DomainId");

                    b.HasIndex("ParentId");

                    b.ToTable("Entries");
                });

            modelBuilder.Entity("Pika.DataLayer.Model.ObjectiveDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("RequiredCount")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Objectives");
                });

            modelBuilder.Entity("Pika.DataLayer.Model.ProjectDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("DomainId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("EntryDbModelObjectiveDbModel", b =>
                {
                    b.HasOne("Pika.DataLayer.Model.EntryDbModel", null)
                        .WithMany()
                        .HasForeignKey("EntriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pika.DataLayer.Model.ObjectiveDbModel", null)
                        .WithMany()
                        .HasForeignKey("ObjectivesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pika.DataLayer.Model.DomainDbModel", b =>
                {
                    b.HasOne("Pika.DataLayer.Model.EntryDbModel", "RootEntry")
                        .WithMany()
                        .HasForeignKey("RootEntryId");

                    b.Navigation("RootEntry");
                });

            modelBuilder.Entity("Pika.DataLayer.Model.EntryDbModel", b =>
                {
                    b.HasOne("Pika.DataLayer.Model.DomainDbModel", "Domain")
                        .WithMany("RelatedEntries")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pika.DataLayer.Model.EntryDbModel", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Domain");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Pika.DataLayer.Model.ObjectiveDbModel", b =>
                {
                    b.HasOne("Pika.DataLayer.Model.ProjectDbModel", "Project")
                        .WithMany("Objectives")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Pika.DataLayer.Model.ProjectDbModel", b =>
                {
                    b.HasOne("Pika.DataLayer.Model.DomainDbModel", "Domain")
                        .WithMany("Projects")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domain");
                });

            modelBuilder.Entity("Pika.DataLayer.Model.DomainDbModel", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("RelatedEntries");
                });

            modelBuilder.Entity("Pika.DataLayer.Model.EntryDbModel", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Pika.DataLayer.Model.ProjectDbModel", b =>
                {
                    b.Navigation("Objectives");
                });
#pragma warning restore 612, 618
        }
    }
}
