name: Pika CICD
on:
  push:
    branches:
      - master
  pull_request: { }
  merge_group:
    types: [ checks_requested ]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: "eu-west-1"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - uses: actions/checkout@v3
      - run: dotnet restore
      - run: dotnet publish -c Release --no-restore -o bin

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: [ build ]
    steps:
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'
      - uses: actions/checkout@v3
      - run: dotnet tool install -g Amazon.Lambda.Tools
      - run: dotnet lambda deploy-function Pika -pl Service -c Release --function-runtime dotnet6 --disable-interactive true
