name: Pika CICD
on:
  push:
    branches:
      - master
  pull_request: { }

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: "eu-west-1"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - uses: actions/checkout@v3
      - run: dotnet restore
      - run: dotnet publish -c Release --no-restore -o bin
        working-directory: Service

  build-image:
    name: Build Image and Push to ECR
    runs-on: ubuntu-latest
#    if: github.ref == 'refs/heads/master'
    steps:
      - name: Log in to ECR
        run: aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 464787150360.dkr.ecr.eu-west-1.amazonaws.com
      - name: Build Image
        run: docker build -t 464787150360.dkr.ecr.eu-west-1.amazonaws.com/pika:latest .
#        working-directory: Service
      - name: Push Image to ECR
        run: docker push 464787150360.dkr.ecr.eu-west-1.amazonaws.com/pika:latest
